import { GoogleGenAI } from "@google/genai";
import { ImageData } from "../types";

// Initialize Gemini SDK with API Key from environment variables
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

// The prompt specifies "Nano Banana" which maps to 'gemini-2.5-flash-image'
const MODEL_NAME = 'gemini-2.5-flash-image';

/**
 * Edits an image using the Gemini 2.5 Flash Image model.
 * 
 * @param sourceImage The source image data (base64 and mimeType).
 * @param prompt The text instruction for editing.
 * @returns The generated image data.
 */
export const editImageWithGemini = async (
  sourceImage: ImageData,
  prompt: string
): Promise<ImageData> => {
  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              data: sourceImage.base64,
              mimeType: sourceImage.mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      // Configuration based on guidelines for image editing
      config: {
        // Nano banana (flash-image) does not support responseMimeType or specific schemas usually for editing, 
        // relying on default behavior to return an image part.
      }
    });

    // Iterate through parts to find the image part as per guidelines
    const parts = response.candidates?.[0]?.content?.parts;

    if (!parts) {
      throw new Error("No content generated by the model.");
    }

    let generatedImage: ImageData | null = null;

    for (const part of parts) {
      if (part.inlineData) {
        const mimeType = part.inlineData.mimeType || 'image/png';
        const base64 = part.inlineData.data;
        generatedImage = {
          base64,
          mimeType,
          url: `data:${mimeType};base64,${base64}`
        };
        break; // Found the image, exit loop
      }
    }

    if (!generatedImage) {
      throw new Error("The model did not return an image. It might have refused the prompt.");
    }

    return generatedImage;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
